### ISSUE TITLE
fix: Layout 수정 요청

### ISSUE THREAD

**Issue by rosenfence** [rosenfence/react-movie-app#16]
![image](https://user-images.githubusercontent.com/90300215/219864767-36a68d1d-6cd3-40f2-b488-53d17b80665a.png)

위 이미지에서 보이는것 처럼 모바일 페이지에서 우측 빈 공간이 발생합니다.

이 부분을 수정해 주세요.

**Comment by HARIN-YU** [comment]
알겠습니다!
