### ISSUE TITLE
[Bug] 가로 스크롤 생기는 문제

### ISSUE THREAD

**Issue by nohack-dev** [rosenfence/react-movie-app#23]
@HARIN-YU @rosenfence 콘텐츠가 모두 보임에도 불구하고, 컨테이너 가로 스크롤이 생기는 문제
<img width="612" alt="image" src="https://user-images.githubusercontent.com/42988225/219985784-4c482a15-f184-486c-918e-515f79c77c63.png">

**Comment by n0hack** [comment]
@HARIN-YU @rosenfence

**Comment by rosenfence** [comment]
#24 해결되었습니다
